name: Build and Publish

on: [push, pull_request]

jobs:
  build_wheels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Install build tools
        run: pip install build
      - name: Build wheel
        run: python -m build --wheel --outdir dist/
      - uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: ./dist/*.whl
          overwrite: true

  upload_pypi:
    needs: [build_wheels]
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: wheels
          path: dist
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: ${{ secrets.pypi_username }}
          password: ${{ secrets.pypi_password }}